Ensure only unique mode of trial reasons are returned
ministryofjustice/laa-court-data-adaptor pull request #355
Opened 2020-12-18 17:05 UTC by chris-groves

## What

https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=454&projectKey=LASB&modal=detail&selectedIssue=LASB-443

Ensure only unique mode of trial reasons are returned

## Checklist

Before you ask people to review this PR:

- [ ] Tests and linters should be passing
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2021-01-04 11:04 UTC, jsugarman commented on app/models/offence.rb
> +    }.uniq.compact
👍

2021-01-04 11:07 UTC, jsugarman requested changes
I think we should remove the uniq.compact from line 77 of`app/models/offence.rb` as well.

Also, we should test this repeated allocation decision scenario if it is not already  - I can't see a test for this.

2021-01-06 15:20 UTC, jsugarman approved these changes
Have amended but would be good to have someone else review.

This should go out asap as it is displaying odd details ATM

2021-01-06 15:34 UTC, msahilan07 approved these changes
LGTM

2021-01-06 15:49 UTC, merged